version: "3.9"

services:
  php:
    image: topalbums-php-fpm
    build:
      context: ./
      dockerfile: ./docker/Dockerfile
    container_name: php
    user: "1000:1000"
    restart: unless-stopped
    environment:
      # - HOME=/app
      - TZ=Europe/Paris
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - app:/app:ro
      # mount bind for dev 
      # - ./app:/app
      # - ./docker/php.ini:/usr/local/etc/php/conf.d/php.ini
    working_dir: "/app"

  nginx:
    image: nginxinc/nginx-unprivileged:alpine
    container_name: nginx
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
      # mount bind for dev 
      # - ./app:/app
      - app:/app:ro
    environment:
      - TZ=Europe/Paris
    ports:
      - 8181:8080
    working_dir: "/app"

volumes:
  app: